# Generated by Django 5.1.1 on 2024-10-09 04:56

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command("loaddata", "polls/fixture/Question_init.json", app_label="polls")
    call_command("loaddata", "polls/fixture/Choice_init.json", app_label="polls")


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
