# Generated by Django 5.1.1 on 2024-11-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_users_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='contentsId',
            new_name='contentId',
        ),
    ]
